version: "3.7"
services:

  proxy:
    build:
      context: ../..
      dockerfile: ./examples/http_call_to_respond/Dockerfile-proxy
    volumes:
      - ../..:/usr/local/lib/rider
      - ./envoy-http-call-to-respond.yaml:/etc/envoy-http-call-to-respond.yaml
    networks:
      - envoymesh
    expose:
      - "80"
      - "8001"
    ports:
      - "8002:80"
      - "8001:8001"

  web_service:
    build:
      context: .
      dockerfile: Dockerfile-web-service
    networks:
      envoymesh:
        aliases:
          - web_service
    expose:
      - "80"
    ports:
      - "8080:80"

networks:
  envoymesh: {}
